name: Deploy API Proxy
description: Deploy the API proxy instance using Proxygen

inputs:
  mtls-secret-name:
    description: 'mTLS secret name for the proxy'
    required: true
  target-url:
    description: 'Target URL to which the proxy will forward requests'
    required: true
  proxy-base-path:
    description: 'A unique base path for the proxy instance'
    required: true
  proxygen-key-secret:
    description: 'Proxygen private key secret'
    required: true
  proxygen-key-id:
    description: 'Proxygen key ID'
    required: true
  proxygen-api-name:
    description: 'Proxygen API name'
    required: true
  proxygen-client-id:
    description: 'Proxygen client ID'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Proxygen
      uses: ./.github/actions/proxy/configure-proxygen
      with:
        proxygen-key-secret: ${{ inputs.proxygen-key-secret }}
        proxygen-key-id: ${{ inputs.proxygen-key-id }}
        proxygen-api-name: ${{ inputs.proxygen-api-name }}
        proxygen-client-id: ${{ inputs.proxygen-client-id }}

    - name: Add PR number to API's title
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash
      run: yq eval '.info.title = "[PR "+env(PR_NUMBER)+"] " + .info.title' -i gateway-api/openapi.yaml

    - name: Inject secrets into openapi.yaml for deploying proxy
      env:
        TARGET_URL: ${{ inputs.target-url }}
        MTLS_SECRET_NAME: ${{ inputs.mtls-secret-name }}
      shell: bash
      run: |
        cat gateway-api/openapi.yaml proxygen/x-nhsd-apim.template.yaml > /tmp/proxy-specification.yaml

        yq eval '.x-nhsd-apim.target.url = env(TARGET_URL) | .x-nhsd-apim.target.security.secret = env(MTLS_SECRET_NAME)' -i /tmp/proxy-specification.yaml

    - name: Deploy API proxy
      env:
        PROXY_BASE_PATH: ${{ inputs.proxy-base-path }}
      shell: bash
      run: |
        proxygen instance deploy internal-dev "$PROXY_BASE_PATH" /tmp/proxy-specification.yaml --no-confirm
