name: Deploy API Proxy
description: Deploy the API proxy instance using Proxygen

inputs:
  mtls-secret-name:
    description: 'mTLS secret name for the proxy'
    required: true
  target-url:
    description: 'Target URL to which the proxy will forward requests'
    required: true
  proxy-base-path:
    description: 'A unique base path for the proxy instance'
    required: true
  proxygen-key-secret:
    description: 'Proxygen private key secret'
    required: true
  proxygen-key-id:
    description: 'Proxygen key ID'
    required: true
  proxygen-api-name:
    description: 'Proxygen API name'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Proxygen
      uses: ./.github/actions/proxy/configure-proxygen
      with:
        proxygen-key-secret: ${{ inputs.proxygen-key-secret }}
        proxygen-key-id: ${{ inputs.proxygen-key-id }}
        proxygen-api-name: ${{ inputs.proxygen-api-name }}

    - name: Inject secrets into openapi.yaml for deploying proxy
      shell: bash
      run: |
        cat gateway-api/openapi.yaml proxygen/x-nhsd-apim.template.yaml > /tmp/proxy-specification.yaml

        yq eval '.x-nhsd-apim.target.url = "${{ inputs.target-url }}" | .x-nhsd-apim.target.security.secret = "${{ inputs.mtls-secret-name }}"' -i /tmp/proxy-specification.yaml

    - name: Deploy API proxy
      shell: bash
      run: |
        proxygen instance deploy internal-dev ${{ inputs.proxy-base-path }} /tmp/proxy-specification.yaml --no-confirm
