#!/bin/bash
set -e

source scripts/env/pds.sh
source scripts/env/sds.sh
source scripts/env/provider.sh
source scripts/env/helper.sh

ENV_FILE=".env"

confirm_overwrite "$ENV_FILE"

PDS_URL=$(prompt_pds_url "$env")
SDS_URL=$(prompt_sds_url "$env")
PROVIDER_URL=$(prompt_provider_url "$env")

cat > "$ENV_FILE" <<EOF
# This file was generated by 'make env-$env'.

PDS_URL=$PDS_URL
PDS_API_TOKEN=
PDS_API_SECRET=
PDS_API_KID=

PROVIDER_URL=$PROVIDER_URL

SDS_URL=$SDS_URL
SDS_API_TOKEN=

CDG_DEBUG=false
EOF

echo "$ENV_FILE for $env written."
