.PHONY: env env-% _env

env:
	make env-dev # TODO: Make this interactive

env-%: # Create .env file with environment variables - optional: name=[name of the environment, e.g. 'dev'] @Configuration
	make _env name="$*" # TODO: Implement difference envs

_env:
	echo "# ENVIRONMENT VARIABLES" > .env
	echo "# ---------------------" >> .env
	echo "# This file is generated by 'make env'/'make env-*'." >> .env

	echo "FLASK_PORT=8080" >> .env
	echo "FLASK_HOST=0.0.0.0" >> .env

	echo "BASE_URL=http://gateway-api:8080" >> .env

	echo "PDS_URL=stub" >> .env
	echo "PROVIDER_URL=stub" >> .env
	echo "SDS_URL=stub" >> .env

	echo "CDG_DEBUG=false" >> .env

${VERBOSE}.SILENT: \
	_env \
	env \
	env-% \
