#!/bin/bash
set -e

source scripts/env/pds.sh
source scripts/env/sds.sh
source scripts/env/provider.sh

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    printf "'%s' already exists. Overwrite? [y/N]: " "$ENV_FILE"
    read -r answer
    case "$answer" in
        [yY]|[yY][eE][sS])
            echo "Overwriting $ENV_FILE..."
            ;;
        *)
            echo "Aborted."
            exit 0
            ;;
    esac
fi

PDS_URL=$(prompt_pds_url "$env")
SDS_URL=$(prompt_sds_url "$env")
PROVIDER_URL=$(prompt_provider_url "$env")

cat > "$ENV_FILE" <<EOF
# This file was generated by 'make env-$env'.

FLASK_PORT=8080
FLASK_HOST=0.0.0.0

BASE_URL=http://gateway-api:8080

PDS_URL=$PDS_URL
PROVIDER_URL=$PROVIDER_URL
SDS_URL=$SDS_URL

CDG_DEBUG=false
EOF

echo "$ENV_FILE for $env written."
