#!/bin/bash
# Use make env-test-<env> to generate a .env.test file for the specified environment.
# See scripts/env/env.mk for the make targets that call this script.
set -e

source scripts/env/target.sh
source scripts/env/helper.sh
source scripts/env/apigee.sh

env="$1"
BASE_URL=$(prompt_base_url "$env")
PROXYGEN_API_NAME=$(prompt_proxygen_api_name "$env")
PROXY_BASE_PATH=$(prompt_proxy_base_path "$env")
if [[ -z "$PROXYGEN_API_NAME" || -z "$PROXY_BASE_PATH" ]]; then
  PROXY_NAME=""
else
  PROXY_NAME="${PROXYGEN_API_NAME}--internal-dev--${PROXY_BASE_PATH}"
fi
APIGEE_ACCESS_TOKEN=$(prompt_apigee_access_token "$env")
TARGET_ENV=$(prompt_target_env "$env")

ENV_FILE=".env.test"
overwrite="$2"
if [[ "$overwrite" != "true" ]]; then
  confirm_overwrite "$ENV_FILE"
fi

cat > "$ENV_FILE" <<EOF
# This file was generated by 'make env-test-$env'.
set -a
APIGEE_ACCESS_TOKEN=${APIGEE_ACCESS_TOKEN}
PROXYGEN_API_NAME=${PROXYGEN_API_NAME}
PROXY_NAME=${PROXY_NAME}
PROXY_BASE_PATH=$PROXY_BASE_PATH
BASE_URL=$BASE_URL
TARGET_ENV=$TARGET_ENV
set +a
EOF

echo "$ENV_FILE for $env written."
