#!/bin/bash
# Use make env-test-<env> to generate a .env.test file for the specified environment.
# See scripts/env/env.mk for the make targets that call this script.
set -e

source scripts/env/test/target.sh
source scripts/env/test/apigee.sh
source scripts/env/test/data.sh

env="$1"
BASE_URL=$(get_base_url "$env")
PROXYGEN_API_NAME=$(get_proxygen_api_name "$env")
PROXY_BASE_PATH=$(get_proxy_base_path "$env")
if [[ -z "$PROXYGEN_API_NAME" || -z "$PROXY_BASE_PATH" ]]; then
  PROXY_NAME=""
else
  PROXY_NAME="${PROXYGEN_API_NAME}--internal-dev--${PROXY_BASE_PATH}"
fi
APIGEE_ACCESS_TOKEN=$(get_apigee_access_token "$env")
TARGET_ENV=$(get_target_env "$env")
REMOTE_TEST_USERNAME=$(get_test_user "$env")
TEST_NHS_NUMBER=$(get_test_nhs_number "$env")

CONSUMER_ODS_CODE=$(get_consumer_ods_code "$env")

ENV_FILE=".env.test"

cat > "$ENV_FILE" <<EOF
# This file was generated by 'make env-test-$env'.
set -a
APIGEE_ACCESS_TOKEN=${APIGEE_ACCESS_TOKEN}
PROXYGEN_API_NAME=${PROXYGEN_API_NAME}
PROXY_BASE_PATH=$PROXY_BASE_PATH

BASE_URL=$BASE_URL

TARGET_ENV=$TARGET_ENV

REMOTE_TEST_USERNAME=$REMOTE_TEST_USERNAME
TEST_NHS_NUMBER=$TEST_NHS_NUMBER
CONSUMER_ODS_CODE=$CONSUMER_ODS_CODE
set +a
EOF

echo "$ENV_FILE for $env written."
