"""Provider contract tests to verify the Flask API meets the consumer contract.

This test suite verifies that the actual Flask provider implementation
satisfies the contracts defined by consumers.
"""

import pytest
from pact import Verifier


class TestProviderContract:
    """Provider contract tests to verify the API implementation."""

    def test_provider_honors_consumer_contract(self, provider_url):
        """Verify that the provider satisfies all consumer contracts.

        This test verifies the Flask API against the pact files
        generated by consumer tests.
        """
        # Create a verifier for the provider
        verifier = Verifier(name="GatewayAPIProvider")

        # Add the transport (how to connect to the provider)
        verifier.add_transport(url=provider_url)

        # Add the pact file as a source
        verifier.add_source(
            "tests/contract/pacts/GatewayAPIConsumer-GatewayAPIProvider.json"
        )

        # Verify the provider against the pact
        try:
            verifier.verify()
        except Exception as e:
            pytest.fail(f"Pact verification failed: {e}")
