name: Tear Down API Proxy
description: Delete the API Gateway proxy through Proxygen

inputs:
  proxy-base-path:
    description: 'A unique base path for the proxy instance'
    required: true
  proxygen-key-secret:
    description: 'Proxygen private key secret from AWS Secrets Manager'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Proxygen CLI
      uses: ./.github/actions/setup-proxygen-cli

    - name: Tear down preview API proxy
      shell: bash
      run: |
        proxygen instance delete internal-dev ${{ inputs.proxy-base-path }} --no-confirm
