#!/bin/bash
set -e

source scripts/env/app/pds.sh
source scripts/env/app/sds.sh
source scripts/env/app/provider.sh

ENV_FILE=".env"

PDS_URL=$(get_pds_url "$env")
PDS_API_TOKEN=$(get_pds_api_token "$env")
PDS_API_SECRET=$(get_pds_api_secret "$env")
PDS_API_KID=$(get_pds_api_kid "$env")

SDS_URL=$(get_sds_url "$env")
SDS_API_TOKEN=$(get_sds_api_token "$env")

PROVIDER_URL=$(get_provider_url "$env")

cat > "$ENV_FILE" <<EOF
# This file was generated by 'make env-$env'.

PDS_URL=$PDS_URL
PDS_API_TOKEN=$PDS_API_TOKEN
PDS_API_SECRET=$PDS_API_SECRET
PDS_API_KID=$PDS_API_KID

PROVIDER_URL=$PROVIDER_URL

SDS_URL=$SDS_URL
SDS_API_TOKEN=$SDS_API_TOKEN

CDG_DEBUG=false
EOF

echo "$ENV_FILE for $env written."
