name: Deploy API Proxy
description: Deploy the API Gateway proxy through Proxygen

inputs:
  mtls-secret-key:
    description: 'mTLS secret key for the proxy'
    required: true
  target-url:
    description: 'Target URL to which the proxy will forward requests'
    required: true
  proxy-base-path:
    description: 'A unique base path for the proxy instance'
    required: true
  proxygen-key-secret:
    description: 'Proxygen private key secret'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Proxygen CLI
      uses: ./.github/actions/setup-proxygen-cli

    - name: Deploy API proxy
      shell: bash
      run: |
        proxygen instance deploy internal-dev ${{ inputs.proxy-base-path }} /tmp/proxy-specification.yaml --no-confirm
