name: "Test Bruno Collection"

env:
  python_version: "3.14"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-run:
    name: "Deploy app and run bruno"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ env.python_version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bruno CLI
        run: npm install --ignore-scripts -g @usebruno/cli

      - name: "Run Bruno"
        working-directory: bruno/gateway-api/collections/Steel_Thread
        run: bru run --env local --reporter-html results.html --reporter-junit results.xml

      - name: "Upload HTML results"
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bruno-results
          path: bruno/gateway-api/collections/Steel_Thread/results.html
          retention-days: 30

      - name: "Publish results"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: bruno/gateway-api/collections/Steel_Thread/results.xml
